
IF (SOURCE_FILES)
	execute_process(COMMAND cmake -DSOURCE_FILES=1 -G${CMAKE_GENERATOR} WORKING_DIRECTORY $ENV{CAFE_SRC}/shared/ksi_libdb)		
	RETURN()
ELSE (SOURCE_FILES)
ENDIF (SOURCE_FILES)

FIND_LIBRARY (ORACLE_LIB NAMES oracle-s PATHS $ENV{CAFE_SRC}/shared/ksi_libdb)

IF (NOT ORACLE_LIB)
	MESSAGE (STATUS "try_compile lib_db lib")
	TRY_COMPILE (BUILD_ORACLE $ENV{CAFE_SRC}/shared/ksi_libdb $ENV{CAFE_SRC}/shared/ksi_libdb OracleClientLibrary CMAKE_FLAGS -DSOURCE_FILES:UNINITIALIZED=0)

	IF (NOT BUILD_ORACLE)
		MESSAGE (FATAL_ERROR "can't build lib_db lib")
	ELSE (NOT BUILD_ORACLE)
		MESSAGE (STATUS "compile lib_db lib successful")
	ENDIF (NOT BUILD_ORACLE)
ENDIF (NOT ORACLE_LIB)
