
IF (SOURCE_FILES)
	execute_process(COMMAND cmake -DSOURCE_FILES=1 -G${CMAKE_GENERATOR} WORKING_DIRECTORY $ENV{CAFE_SRC}/shared/miracle)		
	RETURN()
ELSE (SOURCE_FILES)
ENDIF (SOURCE_FILES)

FIND_LIBRARY (MIRACLE_LIB NAMES miracle-s PATHS $ENV{CAFE_SRC}/shared/miracle)

IF (NOT MIRACLE_LIB)
	MESSAGE (STATUS "try_compile miracle lib")
	TRY_COMPILE (BUILD_MIRACLE $ENV{CAFE_SRC}/shared/miracle $ENV{CAFE_SRC}/shared/miracle MiracleLibrary CMAKE_FLAGS -DSOURCE_FILES:UNINITIALIZED=0)

	IF (NOT BUILD_MIRACLE)
		MESSAGE (FATAL_ERROR "can't build miracle lib")
	ELSE (NOT BUILD_MIRACLE)
		MESSAGE (STATUS "compile miracle lib successful")
	ENDIF (NOT BUILD_MIRACLE)
ENDIF (NOT MIRACLE_LIB)
