
IF (SOURCE_FILES)
	execute_process(COMMAND cmake -DSOURCE_FILES=1 -G${CMAKE_GENERATOR} WORKING_DIRECTORY $ENV{CAFE_SRC}/shared/ksi_order)		
	RETURN()
ELSE (SOURCE_FILES)
ENDIF (SOURCE_FILES)

FIND_LIBRARY (ORDER_LIB NAMES order-s PATHS $ENV{CAFE_SRC}/shared/ksi_order)

IF (NOT ORDER_LIB)
	MESSAGE (STATUS "try_compile order lib")
	TRY_COMPILE (BUILD_ORDER $ENV{CAFE_SRC}/shared/ksi_order $ENV{CAFE_SRC}/shared/ksi_order OrderLibrary CMAKE_FLAGS -DSOURCE_FILES:UNINITIALIZED=0)

	IF (NOT BUILD_ORDER)
		MESSAGE (FATAL_ERROR "can't build order lib")
	ELSE (NOT BUILD_ORDER)
		MESSAGE (STATUS "compile order lib successful")
	ENDIF (NOT BUILD_ORDER)
ENDIF (NOT ORDER_LIB)
