
IF (SOURCE_FILES)
	execute_process(COMMAND cmake -DSOURCE_FILES=1 -G${CMAKE_GENERATOR} WORKING_DIRECTORY $ENV{CAFE_SRC}/shared/printer)		
	RETURN()
ELSE (SOURCE_FILES)
ENDIF (SOURCE_FILES)

FIND_LIBRARY (PRINTER_LIB NAMES printer-s PATHS $ENV{CAFE_SRC}/shared/printer)

IF (NOT PRINTER_LIB)
	MESSAGE (STATUS "try_compile printer lib")
	TRY_COMPILE (BUILD_PRINTER $ENV{CAFE_SRC}/shared/printer $ENV{CAFE_SRC}/shared/printer XmlPrinterLibrary CMAKE_FLAGS -DSOURCE_FILES:UNINITIALIZED=0)

	IF (NOT BUILD_PRINTER)
		MESSAGE (FATAL_ERROR "can't build printer lib")
	ELSE (NOT BUILD_PRINTER)
		MESSAGE (STATUS "compile printer lib successful")
	ENDIF (NOT BUILD_PRINTER)
ENDIF (NOT PRINTER_LIB)
