
IF (SOURCE_FILES)
	execute_process(COMMAND cmake -DSOURCE_FILES=1 -G${CMAKE_GENERATOR} WORKING_DIRECTORY $ENV{CAFE_SRC}/shared/serial)	
	
	RETURN()
ELSE (SOURCE_FILES)
ENDIF (SOURCE_FILES)

FIND_LIBRARY (SERIAL_LIB NAMES serial-s PATHS $ENV{CAFE_SRC}/shared/serial)

IF (NOT SERIAL_LIB)
	MESSAGE (STATUS "try_compile serial lib")
	TRY_COMPILE (BUILD_SERIAL $ENV{CAFE_SRC}/shared/serial $ENV{CAFE_SRC}/shared/serial SerialLibrary CMAKE_FLAGS -DSOURCE_FILES:UNINITIALIZED=0)
	
	IF (NOT BUILD_SERIAL)
		MESSAGE (FATAL_ERROR "can't build serial lib")
	ELSE (NOT BUILD_SERIAL)
		MESSAGE (STATUS "compile serial lib successful")
	ENDIF (NOT BUILD_SERIAL)	
ENDIF (NOT SERIAL_LIB)





