#ifndef __btn_list_f__
#define __btn_list_f__

/**
@file
Subclass of base_btn_list_f, which is generated by wxFormBuilder.
*/

#include "base_btn_list_f.h"
#include <wx/button.h>
#include <wx/sizer.h>
#include <memory>
#include <vector>
#include <map>
#include <wx_util/move_up.hpp>

/** Implementing base_btn_list_f */
class btn_list_f : public base_btn_list_f
{
public:
	/** Constructor */
	btn_list_f( wxWindow* parent, const wxString& caption_, const wxString& footer_, std::vector<wxString>& cap_vec_, std::vector<wxColour>& color_vec_, std::vector<bool>& checked_, std::vector<bool>& enabled_, std::vector<bool>& wrap_);
	btn_list_f( wxWindow* parent, const wxString& caption_, const wxString& footer_, table_show_t* table_show_);
	~btn_list_f();
	void OnClick( wxCommandEvent& event );
	wxButton* getTableBtn() const { return table_btn_; }
private:
	std::vector<wxString> cap_vec_;
	std::vector<wxButton*> btn_vec_;
	std::vector<wxColour> color_vec_;
	std::vector<bool> checked_;
	std::vector<bool> enabled_;
	std::vector<bool> wrap_;
	std::auto_ptr<list_buttons_t> list_;
	table_show_t* table_show_;
	wxButton* table_btn_;
	
	wxFlexGridSizer* fgSizer;
};

#endif // __btn_list_f__
