#ifndef __calc_f__
#define __calc_f__

/**
@file
Subclass of base_calc_f, which is generated by wxFormBuilder.
*/

#include "base_calc_f.h"


/** Implementing base_calc_f */
class calc_f : public base_calc_f
{
protected:
	// Handlers for base_calc_f events.
	void onChar( wxKeyEvent& event );
	void onKeyDown( wxKeyEvent& event );
	void exact_amount_btnClick( wxCommandEvent& event );
	void process_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	void num_btnClick( wxCommandEvent& event );
	void clear_btnClick( wxCommandEvent& event );
	void speed_num_btnClick( wxCommandEvent& event );
	void cash_tendered_edChange( wxCommandEvent& event );
private:
	/** Constructor */
	calc_f( wxWindow* parent );
private:
	double total_;
	bool prepayment_;
	size_t frac_;
	void validControls(double maxPay);
	double diffMoney( wxCommandEvent& event);
	double diffMoney( wxButton* btn );
public:
	/** Constructor */
	calc_f (wxWindow* parent, const wxString& title, double total_, bool prepayment_);
	double amount() const;
};

#endif // __calc_f__
