#ifndef __card_swipe_f__
#define __card_swipe_f__

/**
@file
Subclass of base_card_swipe_f, which is generated by wxFormBuilder.
*/

#include "base_card_swipe_f.h"
#include <wx_util/wx_util.hpp>

/** Implementing base_card_swipe_f */
class card_swipe_f : public base_card_swipe_f
{
protected:
	// Handlers for base_card_swipe_f events.
	void cancel_btnClick( wxCommandEvent& event );
	void OnChar( wxKeyEvent& event );
	void OnLeftMouseUp( wxMouseEvent& event );
public:
	/** Constructor */
	card_swipe_f( wxWindow* parent, const wxString& title, const wxString& label=_("AUTHORIZE CC"));
	~card_swipe_f();
	std::string buff() const { return to_mb(buff_); }
private:
	bool card_reading_;
	bool catch_return_;
	wxString buff_;
};

#endif // __card_swipe_f__
