//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: cashier_ico.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_cashier_ico_H__
#define __WDR_cashier_ico_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "cashier_ico_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

wxBitmap CashierBitmapsFunc( size_t index );

#endif

// End of generated file
