#ifndef __close_order_manager_f__
#define __close_order_manager_f__

/**
@file
Subclass of base_close_order_manager_f, which is generated by wxFormBuilder.
*/

#include "base_close_order_manager_f.h"
#include <map>
#include <string>


/** Implementing base_close_order_manager_f */
class close_order_manager_f : public base_close_order_manager_f
{
private:
	void close_btnClick( wxCommandEvent& event );
	void find_order_btnClick( wxCommandEvent& event );
	void print_receipt_duplicate_btnClick( wxCommandEvent& event );
	void refund_order_btnClick( wxCommandEvent& event );
	void change_payment_type_btnClick( wxCommandEvent& event );
	void reopen_order_btnClick( wxCommandEvent& event );
	
	/** Evetns */
	void sgSelChanged( wxTreeEvent& event );
	void sgSelChanging( wxTreeEvent& event );
	
	/***/
	bool locate(int order_id);
	std::map<int, std::string> payment_type_map;
	std::map<int, int> order_cctrans_count_map;
public:
	/** Constructor */
	close_order_manager_f( wxWindow* parent, const wxString& title);
	~close_order_manager_f();
private:
};

#endif // __close_order_manager_f__
