#ifndef __config_f__
#define __config_f__

/**
@file
Subclass of base_config_f, which is generated by wxFormBuilder.
*/

#include "base_config_f.h"

/** Implementing base_config_f */
class config_f : public base_config_f
{
protected:
	// Handlers for base_config_f events.
	void auto_resolution_chbCheck( wxCommandEvent& event );
	void terminate_app_btnClick( wxCommandEvent& event );
	void cc_processing_rgClick( wxCommandEvent& event );
	void EditFocus( wxFocusEvent& event );
	void test_credentials_btnClick( wxCommandEvent& event );
	void test_printer_btnClick( wxCommandEvent& event );
	void close_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	void local_printer_chbCheck( wxCommandEvent& event );
	void net_printer_chbCheck( wxCommandEvent& event );
	void no_printer_chbCheck( wxCommandEvent& event );
	void license_edClick( wxMouseEvent& event );
	void site_edClick( wxMouseEvent& event );
	void device_edClick( wxMouseEvent& event );
	void user_edClick( wxMouseEvent& event );
	void password_edClick( wxMouseEvent& event );
	void fline_choiceChange( wxCommandEvent& event );
	void sline_choiceChange( wxCommandEvent& event );
	void locale_cbClick( wxCommandEvent& event );
	void select_file_btnClick( wxCommandEvent& event );
	void load_locale_chbCheck( wxCommandEvent& event );
	void stay_on_top_chbCheck( wxCommandEvent& event );
	void order_typeCheck( wxCommandEvent& event );
public:
	/** Constructor */
	config_f( wxWindow* parent, const wxString& title );
};

#endif // __config_f__
