#ifndef __count_f__
#define __count_f__

/**
@file
Subclass of base_count_f, which is generated by wxFormBuilder.
*/

#include "base_count_f.h"

/** Implementing base_count_f */
class count_f : public base_count_f
{
protected:
	// Handlers for base_count_f events.
	void spin_btnDown( wxSpinEvent& event );
	void spin_btnUp( wxSpinEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	count_f( wxWindow* parent, const wxString& caption, int min_, int max_, int cur_val_ );
	int get_count() const { return cur_val_; }
private:
	int min_;
	int max_;
	int cur_val_;
};

#endif // __count_f__
