#ifndef __coupon_list_f__
#define __coupon_list_f__

/**
@file
Subclass of base_btn_list_f, which is generated by wxFormBuilder.
*/

#include "base_btn_list_f.h"
#include <wx/button.h>
#include <wx/sizer.h>
#include <memory>
#include <vector>
#include <map>
#include <wx_util/move_up.hpp>


namespace ksi_cafe {
	class order_t;
}

/** Implementing base_btn_list_f */
class coupon_list_f : public base_btn_list_f
{
public:
	/** Constructor */
	coupon_list_f( wxWindow* parent, const wxString& caption_, const wxString& footer_, ksi_cafe::order_t* order);
	~coupon_list_f();
	void OnClick( wxCommandEvent& event );
private:
	ksi_cafe::order_t* order;
private:
	std::vector<wxString> cap_vec_;
	std::vector<wxButton*> btn_vec_;
	std::vector<wxColour> color_vec_;
	std::vector<bool> checked_vec_;
	std::vector<bool> enabled_vec_;
	std::vector<bool> wrap_vec_;
	std::auto_ptr<list_buttons_t> list_;
	wxFlexGridSizer* fgSizer;
};

#endif // __btn_list_f__
