#ifndef __coupon_calc_f__
#define __coupon_calc_f__

/**
@file
Subclass of base_coupon_calc_f, which is generated by wxFormBuilder.
*/

#include "base_coupon_calc_f.h"
#include <wx_util/wx_util.hpp>
#include <memory>

/** Implementing base_coupon_calc_f */
class coupon_calc_f : public base_coupon_calc_f
{
protected:
	// Handlers for base_coupon_calc_f events.
	void onChar( wxKeyEvent& event );
	void type_btnClick( wxCommandEvent& event );
	void editOnChar( wxKeyEvent& event );
	void num_btnClick( wxCommandEvent& event );
	void clear_btnClick( wxCommandEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	//coupon_calc_f( wxWindow* parent, double subtotal_, ksi_cafe::base_currency_t* currency, const wxString& cap1 = _("Discount in percent"), const wxString& cap2 = _("Discount in $"));
	coupon_calc_f( wxWindow* parent, double subtotal_, const wxString& cap1, const wxString& cap2);
	double discount_amount() const;
private:
	std::auto_ptr<toggle_group_t> type_toggle_group_ptr;
	double subtotal_;
	wxObject* press_;
};

#endif // __coupon_calc_f__
