#ifndef __dlg_f__
#define __dlg_f__

/**
@file
Subclass of base_dlg_f, which is generated by wxFormBuilder.
*/

#include "base_dlg_f.h"
#include <wx/button.h>
#include <wx/sizer.h>
#include <vector>

/** Implementing base_dlg_f */
class dlg_f : public base_dlg_f
{
public:
	/** Constructor */
	dlg_f( wxWindow* parent, const wxString& cap_, const wxString& lab_,  std::vector<wxString>& cap_vec_, std::vector<wxColour>& color_vec_);
	~dlg_f();
	void OnClick( wxCommandEvent& event );
private:
	std::vector<wxButton*> btn_vec_;
};

#endif // __dlg_f__
