#ifndef __info_f__
#define __info_f__

/**
@file
Subclass of base_info_f, which is generated by wxFormBuilder.
*/

#include "base_info_f.h"
#include <wx_util/wx_util.hpp>

/** Implementing base_info_f */
class info_f : public base_info_f
{
protected:
	// Handlers for base_info_f events.
	void close_btnClick( wxCommandEvent& event );
	void OnTimer (wxTimerEvent& event);
public:
	/** Constructor */
	info_f( wxWindow* parent, const wxString& title, const wxString& label, const wxString& change, bool close_);
private:
	wx_timer_t<info_f> timer_;
};

#endif // __info_f__
