#ifndef __input_num_f__
#define __input_num_f__

/**
@file
Subclass of base_input_num_f, which is generated by wxFormBuilder.
*/

#include "base_input_num_f.h"
#include <wx_util/wx_util.hpp>
#include <ksi_util/format.hpp>
#include <memory>

/** Implementing base_input_num_f */
class input_num_f : public base_input_num_f
{
protected:
	// Handlers for base_input_num_f events.
	void onChar( wxKeyEvent& event );
	void btnClick( wxCommandEvent& event );
	void clear_btnClick( wxCommandEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );	
public:
	/** Constructor */
	input_num_f( wxWindow* parent, const wxString& title, const ksi_cafe::base_format_t& format);
	input_num_f( wxWindow* parent, const wxString& title, bool currency_); 
	void set_format_value(const wxString& val);
	void set_unformat_value(const wxString& val);
	wxString format_text() const;
	wxString unformat_text() const;
	double value() const;
private:
	std::auto_ptr<ksi_cafe::base_format_t> format_;
	bool currency_;
};

#endif // __input_num_f__
