#ifndef __load_f__
#define __load_f__

/**
@file
Subclass of base_load_f, which is generated by wxFormBuilder.
*/

#include "base_load_f.h"
#include <boost/thread.hpp>
#include <boost/bind.hpp>
#include <wx_util/wx_util.hpp>

/** Implementing base_load_f */
class load_f : public base_load_f
{
public:
	/** Constructor */
	load_f( wxWindow* parent, const wxString& title, const wxString& label);
public:
	template<typename Callble>
	void start(Callble func) {
		thr_ = boost::thread(func);
		timer_.start2(5);
	}
	void cancel_btnClick( wxCommandEvent& event ) {
		timer_.stop();
		try {
			thr_.interrupt();
		}
		catch (boost::thread_interrupted& ex) {
		}
		thr_.join();
		EndModal(wxID_CANCEL);
	}
private:
	void OnTimer (wxTimerEvent& event);
private:
	boost::thread thr_;
	wx_timer_t<load_f> timer_;
};

#endif // __load_f__
