#ifndef __manual_entry_f__
#define __manual_entry_f__

/**
@file
Subclass of base_manual_entry_f, which is generated by wxFormBuilder.
*/

#include "base_manual_entry_f.h"

/** Implementing base_manual_entry_f */
class manual_entry_f : public base_manual_entry_f
{
protected:
	// Handlers for base_manual_entry_f events.
	void num_btnClick( wxCommandEvent& event );
	void clear_btnClick( wxCommandEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	void card_numFocus( wxFocusEvent& event );
	void monthFocus( wxFocusEvent& event );
	void yearFocus( wxFocusEvent& event );
	void cvv2Focus( wxFocusEvent& event );
public:
	/** Constructor */
	manual_entry_f( wxWindow* parent, const wxString& title );
	wxString card_num() const { return card_num_ed->GetValue(); }
	wxString exp_month() const { return exp_month_ed->GetValue(); }
	wxString exp_year() const { 
		if (exp_year_ed->GetValue().Length() == 1) return _("200") + exp_year_ed->GetValue();
		else if (exp_year_ed->GetValue().Length() == 2) return _("20") + exp_year_ed->GetValue();
		else if (exp_year_ed->GetValue().Length() == 3) return _("2") + exp_year_ed->GetValue();
		return exp_year_ed->GetValue(); 
	}
	wxString cvv2() const { return cvv2_ed->GetValue(); }
private:
	wxWindow* active_;
};

#endif // __manual_entry_f__
