#ifndef __menu_grid_f__
#define __menu_grid_f__

/**
@file
Subclass of base_menu_grid_f, which is generated by wxFormBuilder.
*/

#include "base_menu_grid_f.h"
#include <ksi_order/menu_container.hpp>
#include <map>

/** Implementing base_menu_grid_f */
class menu_grid_f : public base_menu_grid_f
{
protected:
	// Handlers for base_menu_grid_f events.
	void menu_click( wxCommandEvent& event );

public:
	/** Constructor */
	menu_grid_f( wxWindow* parent );
public:
  void add(ksi_cafe::menu_t* menu);
  void select(ksi_cafe::menu_t* menu);
  ksi_cafe::menu_t* selected();
private:
  std::map<int, ksi_cafe::menu_t*> kv_menu_;
};

#endif // __menu_grid_f__
