#ifndef __select_date_f__
#define __select_date_f__

/**
@file
Subclass of base_select_date_f, which is generated by wxFormBuilder.
*/

#include "base_select_date_f.h"
#include <wx/button.h>
#include <boost/date_time/gregorian/gregorian.hpp>
#include <vector>
#include <map>

/** Implementing base_select_date_f */
class select_date_f : public base_select_date_f
{
protected:
	virtual void ok_btnClick( wxCommandEvent& event );
	virtual void cancel_btnClick( wxCommandEvent& event );
	void btn_click( wxCommandEvent& event );
public:
	/** Constructor */
	select_date_f( wxWindow* parent, const wxString& title, const std::vector<boost::gregorian::date>& date_, const std::vector<int>& enable_, const boost::gregorian::date& selected_ );
	~select_date_f();
	boost::gregorian::date selected() const { return selected_; }
private:
	std::vector<boost::gregorian::date> date_;
	std::vector<int> enable_;
	boost::gregorian::date selected_;
	std::map<wxButton*, boost::gregorian::date> btn_date_map_;
};

#endif // __select_date_f__
