#ifndef __select_time_f__
#define __select_time_f__

/**
@file
Subclass of base_select_time_f, which is generated by wxFormBuilder.
*/

#include "base_select_time_f.h"
#include <boost/date_time/posix_time/posix_time.hpp>
#include <map>

/** Implementing base_select_time_f */
class select_time_f : public base_select_time_f
{
protected:
	// Handlers for base_select_time_f events.
	void m_btnClick( wxCommandEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	select_time_f( wxWindow* parent, const wxString& title_, const boost::posix_time::time_period& period_, int setup_minutes_);
	~select_time_f();
	boost::posix_time::ptime selected() const { return selected_; }
private:
	void btn_click( wxCommandEvent& event );
	boost::posix_time::time_period period_;
	int setup_minutes_;
	std::map<wxButton*, boost::posix_time::ptime> btn_date_time_map_;
	std::map<wxButton*, int> require_conform_;
	std::map<wxButton*, boost::posix_time::time_duration> btn_time_duration_map_;
	boost::posix_time::ptime selected_;
	wxString title_;
};

#endif // __select_time_f__
