#ifndef __split_order_f__
#define __split_order_f__

/**
@file
Subclass of base_split_order_f, which is generated by wxFormBuilder.
*/

#include "base_split_order_f.h"
#include <memory>

namespace ksi_cafe {
	class order_t;
}

/** Implementing base_split_order_f */
class split_order_f : public base_split_order_f
{
protected:
	// Handlers for base_split_order_f events.
	void sourceSpinDownClick( wxSpinEvent& event );
	void sourceSpinUpClick( wxSpinEvent& event );
	void move_from_source_btnClick( wxCommandEvent& event );
	void move_to_source_btnClick( wxCommandEvent& event );
	void destinationSpinDownClick( wxSpinEvent& event );
	void destionationSpinUpClick( wxSpinEvent& event );
	void destination_table_btnClick( wxCommandEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	
protected:
	void source_sgSelChanged(wxTreeEvent& event);
	void source_sgSelChanging(wxTreeEvent& event);
	void destination_sgSelChanged(wxTreeEvent& event);
	void destination_sgSelChanging(wxTreeEvent& event);

	void recalc_coupon(const std::string&, const std::string&);
public:
	/** Constructor */
	split_order_f( wxWindow* parent, const wxString& title, ksi_cafe::order_t* order_);
	~split_order_f();
private:
	ksi_cafe::order_t* order_;
	std::auto_ptr<ksi_cafe::order_t> destination_order;
};

#endif // __split_order_f__
