#ifndef __tip_amount_f__
#define __tip_amount_f__

/**
@file
Subclass of base_tip_amount_f, which is generated by wxFormBuilder.
*/

#include "base_tip_amount_f.h"

/** Implementing base_tip_amount_f */
class tip_amount_f : public base_tip_amount_f
{
protected:
	// Handlers for base_tip_amount_f events.
	void btnClick( wxCommandEvent& event );
	void clear_btnClick( wxCommandEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	void hide_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	tip_amount_f( wxWindow* parent, const wxString& title, double amount, bool hide );
	double tip() const;
private:
};

#endif // __tip_amount_f__
