#ifndef __options_f__
#define __options_f__

/**
@file
Subclass of base_options_f, which is generated by wxFormBuilder.
*/

#include "base_options_f.h"

/** Implementing base_options_f */
class options_f : public base_options_f
{
protected:
	// Handlers for base_options_f events.
	void m_printer_portChoice( wxCommandEvent& event );
	void m_command_setChoice( wxCommandEvent& event );
	void m_baud_rateChoice( wxCommandEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	options_f( wxWindow* parent, const wxString& port, const wxString& cset, const wxString& rate);
	wxString get_printer_port() const;
	wxString get_command_set() const;
	wxString get_baud_rate() const;
};

#endif // __options_f__
