#ifndef __main_f__
#define __main_f__

/**
@file
Subclass of base_main_f, which is generated by wxFormBuilder.
*/

#include "base_main_f.h"
#include <wx_util/wx_util.hpp>
#include <wx_util/move_up.hpp>
#include <vector>
#include <memory>

/** Implementing base_main_f */
class main_f : public base_main_f
{
protected:
	// Handlers for base_main_f events.
	void browse_delayed_orders_btnClick( wxCommandEvent& event );
	void open_orders_btnClick( wxCommandEvent& event );
	void logout_btnClick( wxCommandEvent& event );
	void open_cash_drawer_btnClick( wxCommandEvent& event );
	void close_order_operation_btnClick( wxCommandEvent& event );
	void cash_advance_btnClick( wxCommandEvent& event );
	void create_to_go_order_btnClick( wxCommandEvent& event );
	void create_delivery_order_btnClick( wxCommandEvent& event );
	void create_pickup_order_btnClick( wxCommandEvent& event );
	void create_employee_meal_order_btnClick( wxCommandEvent& event );
	void create_table_booking_order_btnClick( wxCommandEvent& event );
	void OnConfigDbClick( wxMouseEvent& event );
private:
	void resume_wait();
private:
	wx_timer_t<main_f> timer_;
	wx_timer_t<main_f> seance_timer_;
	wx_timer_t<main_f> lock_timer_;
	bool auto_lock_;
private:	
	/** Methods */
	void OnTimer (wxTimerEvent& event);
	void OnSeanceTimer(wxTimerEvent& event);
	void OnLockTimer(wxTimerEvent& event);
	void tableClick( wxCommandEvent& event );
private:
	void logout();
	void btn_repaint();
	void refresh_order_list();
	void apply_lang();
private:
	int delayed_order_count_;
	int open_cash_advance_count_;
	int open_order_count_;
private:
	std::vector<wxButton*> table_vec_;
	std::auto_ptr<table_show_t> table_show_;
	bool needLock;
public:
	/** Constructor */
	main_f( wxWindow* parent );
};

#endif // __main_f__
