//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: HR_ico.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __HR_ico_H__
#define __HR_ico_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "HR_ico.h"
#endif

// Include wxWidgets' headers

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

wxBitmap HR_ico( size_t index );

wxBitmap HR_splash( size_t index );

wxBitmap HR_tool( size_t index );

wxBitmap HR_sort( size_t index );

#endif

// End of generated file
