#ifndef __text_f__
#define __text_f__

/**
@file
Subclass of base_text_f, which is generated by wxFormBuilder.
*/

#include "base_text_f.h"
#include <map>
#include <wx_util/wx_util.hpp>
#include <ksi_util/currency.hpp>

/** Implementing base_text_f */
class text_f : public base_text_f
{
protected:
	// Handlers for base_text_f events.
	void text_edFocus( wxFocusEvent& event );
	void amount_edFocus( wxFocusEvent& event );
	void btnClick( wxCommandEvent& event );
	void bs_btnClick( wxCommandEvent& event );
	void enter_btnClick( wxCommandEvent& event );
	void shift_btnClick( wxCommandEvent& event );
	void kbd_btnClick( wxCommandEvent& event );
	void space_btnClick( wxCommandEvent& event );
	void ok_btnClick( wxCommandEvent& event );
	void cancel_btnClick( wxCommandEvent& event );
	std::map<wxButton*, wxString> us_up_;
	std::map<wxButton*, wxString> us_low_;
	std::map<wxButton*, wxString> ru_up_;
	std::map<wxButton*, wxString> ru_low_;
public:
	/** Constructor */
	text_f( wxWindow* parent, const wxString& title, const wxString& text_title, ksi_cafe::base_currency_t* currency, bool passwd_=false);
	void text(const wxString& str) { text_ed->SetValue(str); }
	wxString text() const { return text_ed->GetValue(); }
	wxString amount() const { return amount_ed->GetValue(); }
private:
	void apply_kbd();
private:
	int kbd_; // 1 - us, 2 - ru
	int kbd_case_; // 0 - low, 1 - up
	wxWindow* active_;
	ksi_cafe::base_currency_t* currency;
	bool passwd_;
};

#endif // __text_f__
